apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xwiki-app
  name: xwiki-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: xwiki-app
  template:
    metadata:
      labels:
        app: xwiki-app
    spec:
      containers:
      - image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/SERVICE:TAG
        imagePullPolicy: IfNotPresent
        name: xwik
      terminationGracePeriodSeconds: 30