name: Build and Push xwiki WAR

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build/Deploy with Maven
        run: mvn -P distribution,snapshot -pl org.xwiki.platform:xwiki-platform-distribution-jetty-hsqldb -Dmaven.test.skip=true clean deploy

      - name: Copy zip to GCS
        id: 'upload-zip'
        uses: 'google-github-actions/upload-cloud-storage@v1'
        with:
          path: './xwiki-platform-distribution/xwiki-platform-distribution-jetty-hsqldb/target'
          glob: '*.zip'
          destination: 'xwiki-release'
          gzip: false
