name: Deploy xwiki to Cloud Run

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          export_environment_variables: true

      - name: Build and Push Container
        run: |-
          docker build -t gha-test --build-arg GCLOUD_KEY_FILE_CONTENT='${{ secrets.GOOGLE_CREDENTIALS }}' ./

