name: Deploy xwiki to Cloud Run

on: [workflow_dispatch]

env:
  PROJECT_ID: kmonty-test
  GAR_LOCATION: us-central1
  REPOSITORY: xwiki-docker-repo
  SERVICE: xwik
  REGION: us-central1
  DEPLOYMENT_NAME: xwiki-app

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          export_environment_variables: true

      - name: Authenticate to AR
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: _json_key
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'
          password: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Build and Push Container
        run: |-
          docker build --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA" --build-arg GCLOUD_KEY_FILE_CONTENT='${{ secrets.GOOGLE_CREDENTIALS }}' ./
          docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA"

      - name: Set up Kustomize
        run: |-
          curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
          chmod u+x ./kustomize

      - name: Deploy
        run: |-
          # replacing the image name in the k8s template
          ./kustomize edit set image LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/SERVICE:TAG=$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$SERVICE:$GITHUB_SHA
          ./kustomize build . | kubectl apply -f -
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide

