name: Deploy xwiki to Cloud Run

on: [workflow_dispatch]

env:
  PROJECT_ID: kmonty-test
  GAR_LOCATION: us-central1
  REPOSITORY: xwiki-docker-rep
  SERVICE: xwik
  REGION: us-central1
  
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
          export_environment_variables: true

      - name: Authenticate to AR
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          registry: '${{ env.GAR_LOCATION }}-docker.pkg.dev'

      - name: Build and Push Container
        run: |-
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" --build-arg GCLOUD_KEY_FILE_CONTENT='${{ secrets.GOOGLE_CREDENTIALS }}' ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

